In [15]:
import pandas as pd

# df = pd.read_csv(
#     './data/raw/ml-10M100K/ratings.dat',
#     # usecols = ['userId', 'movieId', 'rating', 'timestamp'],
#     sep='::',
#     header=None,
#     # low_memory = False
# )

df = pd.read_csv(
    './data/raw/ml-10M100K/ratings.csv',
    # usecols = ['userId', 'movieId', 'rating', 'timestamp'],
    # sep='::',
    # header=None,
    # low_memory = False
)

In [16]:
df.shape

(10000054, 4)

In [17]:
df

          userId  movieId  rating  timestamp
0              1      122     5.0  838985046
1              1      185     5.0  838983525
2              1      231     5.0  838983392
3              1      292     5.0  838983421
4              1      316     5.0  838983392
...          ...      ...     ...        ...
10000049   71567     2107     1.0  912580553
10000050   71567     2126     2.0  912649143
10000051   71567     2294     5.0  912577968
10000052   71567     2338     2.0  912578016
10000053   71567     2384     2.0  912578173

[10000054 rows x 4 columns]

In [18]:
list(sorted(set(df.rating)))

[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

In [19]:
len(set(df.userId))

69878

In [20]:
len(set(df.movieId))

10677

In [21]:
df = (
    df
    .pivot(index=['userId'], columns=['movieId'], values='rating')
    # .fillna(0.0)
)
df.shape

(69878, 10677)

In [22]:
df

movieId,1,2,3,4,5,6,7,8,9,10,...,65006,65011,65025,65027,65037,65088,65091,65126,65130,65133
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71564,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71565,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71566,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.to_csv(
    './data/gold/ml10m_pivoted_na.csv',
    header = False,
    index = False,
)